### ISSUE TITLE
Expose Data Object For Each cell

### ISSUE THREAD

**Issue by pakkle** [generic-ui/generic-ui#10]
While it is possible to access one data field in each cell:

`      field: 'amount',
      type: GuiDataType.NUMBER,
      view: (value: number) => {
      ...
`
It is impossible to have access to the whole object.

Potencial solution could be this notation:

`      field: 'amount',
      type: GuiDataType.NUMBER,
      view: (value: number, data: any) => {
      ...
`

**Comment by generic-ui** [comment]
Another great idea, which is easy to implement. Thank @pakkle
