### ISSUE TITLE
Scroll to the row

### ISSUE THREAD

**Issue by pakkle** [generic-ui/generic-ui#12]
It would be nice to be able to skip to the row using its id or index in virtual scroll and pagination mode.

**Comment by generic-ui** [comment]
We can provide a method via on the global API object, which will allow you to scroll grid to wanted row. Will this solution match your needs ?

**Comment by pakkle** [comment]
Sure that will definitely work! Thank you!

**Comment by pakkle** [comment]
Also with virtual scroll it would be nice to have a call back which informs about the change of the current record displayed on the top of the grid or scrollPosition.

**Comment by pakkle** [comment]
Does 0.12.4 address the subject or the previous column? I installed it but did not find how to achieve neither of these two things. Thanks!

**Comment by generic-ui** [comment]
We plan to include this feature in the next hotfix release 0.12.5. I think it will be relased before sunday the 13th.

**Comment by pakkle** [comment]
Thank you very much!!!

**Comment by pakkle** [comment]
hi! Any ETA for 0.12.5 be ready?

**Comment by generic-ui** [comment]
This change is more complicated than we have previously estimated. Please have in mind that we try our best to deliver as fast as we can.

**Comment by pakkle** [comment]
Thank you for the update!

**Comment by generic-ui** [comment]
New 'Viewport' methods has been added to the api https://generic-ui.com/guide/api.

![Screenshot 2020-10-18 at 21 48 46](https://user-images.githubusercontent.com/48868674/96378363-b9302a80-118b-11eb-8194-d701c5d6e0fc.png)

**Comment by pakkle** [comment]
I tested scrollToRowByIndex() and it works perfectly! Thank you!
