### ISSUE TITLE
Editable field is smaller than original text cell

### ISSUE THREAD

**Issue by pakkle** [generic-ui/generic-ui#14]
When in editable mode area dedicated for the editor seems of the fixed size and can be much smaller than the cell itself, which hides original or new text to be edited.

1. Just have a long enough cell in the edit mode with long text to be edited
2. Click on in that cell
3. See that the text and the area is taken just a fraction of the cell

Editable area should take the whole cell minus what is defined with padding style

**Comment by generic-ui** [comment]
Hm, I tested in on the example https://generic-ui.com/demo, it seems to work. Could you be more specific ?
![Screenshot 2020-09-11 at 09 00 21](https://user-images.githubusercontent.com/48868674/92880092-f4617000-f40d-11ea-9c30-bcf77321245a.png)

**Comment by pakkle** [comment]
That is exactly it. The edit field is just a 3rd of the cell width:

<img width="451" alt="input" src="https://user-images.githubusercontent.com/32244934/92926016-66838600-f409-11ea-9daf-97e9281634cf.png">

**Comment by generic-ui** [comment]
Edit feature outlines the whole cell, so user can have the better understanding of the edited content.

The issue here is that you should see the start of the string and not the end of it.

**Comment by pakkle** [comment]
No, the issue is that editable area is fixed in size and is much narrower than the fields itself. I suggest to use whole area. As for scrolling to the end of the line - I see not issue with that. Just the width of the area.

**Comment by generic-ui** [comment]
Thanks for pointing it out. We will take a closer look into this matter.

**Comment by generic-ui** [comment]
Release https://github.com/generic-ui/generic-ui/releases/tag/0.13.0 resolves the issue.

**Comment by pakkle** [comment]
Confirrmed. Thank you!
