### ISSUE TITLE
Language localization

### ISSUE THREAD

**Issue by grimaldistudio** [generic-ui/generic-ui#15]
Hi, is there a way to enable label translation?

**Comment by generic-ui** [comment]
Hey @grimaldistudio can you please be more specific. Which label you would like to translate ?

**Comment by grimaldistudio** [comment]
Sorry. I try to explain myself better. 
is there any way to translate the strings used in generic-ui?
Pages->Pagine, Next->Avanti, etc..

Tnx

**Comment by generic-ui** [comment]
We have already finished implemented localization and it will be released with the next major release.

**Comment by grimaldistudio** [comment]
This is good news! Very well thanks.

**Comment by generic-ui** [comment]
https://generic-ui.com/guide/localization
