### ISSUE TITLE
headers styling

### ISSUE THREAD

**Issue by Toine14** [generic-ui/generic-ui#18]
First of all thank you very much for providing such a usefull tool. It's a great project

**Is your feature request related to a problem? Please describe.**
I have data to show that need big size headers with long text (e.g: phosphorus concentration (µg/L)).
As I have a lot of column to display, even on big size screens, the column header text is often not displayed entirely.

**Describe the solution you'd like**
Is it possible to put column header text on 2 lines increasing the height of headers?

Again, thank you very much!

**Comment by generic-ui** [comment]
Thanks @Toine14 great feature suggestion.
