### ISSUE TITLE
Unable to set relevant access for a particular cell of a particular row.

### ISSUE THREAD

**Issue by VenkammaShalavadi** [generic-ui/generic-ui#23]
My grid contains multiple rows of data and I need to give read only access for particular cell and as well as row based on cell value and give write access for other cells as well as rows. But I am just able to set either read only or write access for entire grid. Is there a feature that I can use to implement the above case.

**Comment by generic-ui** [comment]
Hi @VenkammaShalavadi ,

We have introduced in the latest version 0.16.0 new feature that allows you to specify edit ability of row or cell. You can read about it more in the documentation here https://generic-ui.com/guide/cell-editing
