### ISSUE TITLE
Unable to set relevant access for a particular cell of a particular row.

### ISSUE THREAD

**Issue by varunvarma799** [generic-ui/generic-ui#24]
My grid contains multiple rows of data. I need to give read-only access for particular cells and rows based on a cell value and give write access for other cells as well as rows. But I am just able to set either read-only or write access for the entire grid. Is there a feature that I can use to implement the above case?

**Comment by generic-ui** [comment]
Hello @varunvarma799 ,

Please take a look at this thread https://github.com/generic-ui/generic-ui/issues/23#issuecomment-960499787
