### ISSUE TITLE
GuiSelectedRow New Structure

### ISSUE THREAD

**Issue by pakkle** [generic-ui/generic-ui#33]
Before 0.14.2 (and maybe 0.14.1) **GuiSelectedRow** had property **data** for row object storage. Now property **source** is populated with the row object instead. However GuiSelectedRow definition still have **data** which prevents code compilation.

Can you fix that please?

**Comment by generic-ui** [comment]
Thanks for reporting this bug 👍 . This will be fixed with the next release.

**Comment by generic-ui** [comment]
This issue has been fixed with the 0.15.0 release

**Comment by pakkle** [comment]
Fixed.
