### ISSUE TITLE
How to disable row selection (rowSelecting = false)

### ISSUE THREAD

**Issue by sakshimorya90** [generic-ui/generic-ui#37]
Please tell me about row selection how to disable , because i am using "rowSelecting = false" but it's not working because when i am going to check at dev tools it's working. So please give me a solution.
![Screenshot from 2021-10-14 11-40-48](https://user-images.githubusercontent.com/92502396/137261907-313c0538-e942-4b3b-89c5-bfca2b87dfca.png)

I have attached a screenshot , so please look at give me a solution.

**Comment by generic-ui** [comment]
Hello @sakshimorya90,

It should be `rowSelection` instead of `rowSelecting`. I see there is a small error in the guide, we will fix that.

**Comment by sakshimorya90** [comment]
Thanks it's working fine. but you please correct at document also, because we are all follow you document's.
