### ISSUE TITLE
Header Class

### ISSUE THREAD

**Issue by marvinsy** [generic-ui/generic-ui#43]
Is there a way to apply a stylesheet for the header without using the themes? Thanks!

**Comment by generic-ui** [comment]
Hello @marvinsy,

It is possible to modify a column header with css. You can check the example https://generic-ui.com/examples/agile-users

Please let me know if you need more help.

**Comment by marvinsy** [comment]
Thanks for the quick reply and guide. I have applied the css now and it works like charm! Thanks again!

**Comment by generic-ui** [comment]
I'm glad. Please let me know if you have any other question.

**Comment by generic-ui** [comment]
Hi again @marvinsy ,

We have prepared this new feature with the documentation. It allows you to specify css classes and styles for each column. Please have a look https://generic-ui.com/guide/column-header.

**Comment by marvinsy** [comment]
This is so nice. I like it that you can now edit the styles of the header on the initialization of the columns. ten thumbs up! 👍👍👍👍👍👍👍👍👍👍
