### ISSUE TITLE
Compatibility for latest versions of Angular

### ISSUE THREAD

**Issue by d-jayconwi** [generic-ui/generic-ui#44]
I am starting a project for my company and now in the process of choosing a third party data table tool.
I found out that generic-ui suites our needs but our project is running on Angular 13.
It seems that generic-ui doesn't support Angular 13 yet and throws the error below when installing it: 

> npm ERR! While resolving: conceptshare-web@0.0.0
> npm ERR! Found: @angular/common@13.0.2
> npm ERR! node_modules/@angular/common
> npm ERR!   @angular/common@"~13.0.0" from the root project
> npm ERR!
> npm ERR! Could not resolve dependency:
> npm ERR! peer @angular/common@"12.2.11" from @generic-ui/ngx-grid@0.16.4
> npm ERR! node_modules/@generic-ui/ngx-grid
> npm ERR!   @generic-ui/ngx-grid@"*" from the root project

I tried installing it by using `--force` and it pushed through.

After that I added `GuiGridModule` in my module and tried putting the `<gui-grid>` in my component but now causing this error

> ./node_modules/@generic-ui/fabric/__ivy_ngcc__/fesm2015/generic-ui-fabric.js:6:0-49 - Error: Module not found: Error: Resolving to directories is not possible with the exports field (request was ./)

- When can you support Angular versions >12? 
- Do you have remedy for the `Module not found` error?

**Comment by generic-ui** [comment]
Hey @d-jayconwi ,

We are working on it. Right now @generic-ui/ngx-grid is prepared for the latest angular 12 version. The Angular team introduced lots of changes with the 13 version. It requires lots of work and isn't as easy as we thought.  Nevertheless, we are working on it.

**Comment by d-jayconwi** [comment]
Thanks for that, I'll be using Angular 12 for now
