### ISSUE TITLE
In Angular 13 getting below issue

### ISSUE THREAD

**Issue by thimmappa-splashbi** [generic-ui/generic-ui#48]
**./node_modules/@generic-ui/fabric/__ivy_ngcc__/fesm2015/generic-ui-fabric.js:6:0-49 - Error: Module not found: Error: Resolving to directories is not possible with the exports field (request was ./)**

**Comment by generic-ui** [comment]
Hello @thimmappa-splashbi,
The new version 0.17.0, it now supports Angular 13.
