### ISSUE TITLE
Support for horizontal scrolling

### ISSUE THREAD

**Issue by micdenny** [generic-ui/generic-ui#6]
As far as I see the grid only supports vertical scrolling, could it be possible to support horizontal scrolling for high number of columns?

**Comment by generic-ui** [comment]
Thanks for the great suggestion. Right now we are in the process of rebuilding mechanism for presenting columns, so you can expect for this feature to appear in the future releases. 

Displaying a higher number of columns can be achieved with the use of external wrapper which adds a horizontal scroll. Something like this:

```
.grid-wrapper {
    overflow-x: scroll;
    width: 100%;
}
