### ISSUE TITLE
I want to select the information and delete it.

### ISSUE THREAD

**Issue by themesanasang** [generic-ui/generic-ui#7]
-> I want to select the information and delete it.
-> I want add checkbox multi to select data and delete it. 
No samples to study

**Comment by generic-ui** [comment]
Can you please provide more information:
1) Do you use jQuery or Angular?
2) Are you interested in context (inline) delete or more global delete?

**Comment by themesanasang** [comment]
> 
> 
> Can you please provide more information:
> 
>     1. Do you use jQuery or Angular?
> 
>     2. Are you interested in context (inline) delete or more global delete?

1 Angular
2 I want delete one row and multi row on datatable

**Comment by generic-ui** [comment]
We are currently working on providing an example for you. It will be available soon on the website.

**Comment by themesanasang** [comment]
> We are currently working on providing an example for you. It will be available soon on the website.

thank

**Comment by generic-ui** [comment]
We have prepared a description of rowSelection mechanism in the grid component. Please check out this article https://generic-ui.com/guide/row-select. It also presents how to delete selected item from the grid. Let us know if you have more questions.

**Comment by themesanasang** [comment]
> 
> 
> We have prepared a description of rowSelection mechanism in the grid component. Please check out this article https://generic-ui.com/guide/row-select. It also presents how to delete selected item from the grid. Let us know if you have more questions.

Very good. thank
